### ISSUE TITLE
Feature Request: Allow enclosure lighting to remain on when tool head is unpowered

### ISSUE THREAD

**Issue by OrionPirate** [Snapmaker/Snapmaker2-Controller#10]
Not certain this is firmware rather than hardware, but if it is firmware:

Disconnecting a tool head from the power bus causes the enclosure LED lighting to turn off, and it cannot be turned on until a tool head is attached to power. 

This makes changing tool head inside the enclosure MUCH more awkward, as lighting would be incredibly helpful in this specific case!

**Comment by scotthsl** [comment]
Want to confirm firstly you unplugged your tool head while keeping the controller power on?

**Comment by OrionPirate** [comment]
correct. 

snapmaker was powered on, enclosure lights were on. I unplugged the cable from the tool head, and the enclosure lights went out. Controller was still connected to the snapmaker at the time.

**Comment by scotthsl** [comment]
> correct.
> 
> snapmaker was powered on, enclosure lights were on. I unplugged the cable from the tool head, and the enclosure lights went out. Controller was still connected to the snapmaker at the time.

Hi OrionPirate,

Got your needs, will try to improve the operations to change tool head.

 But please do not plug / unplug tool heads or any other modules again while controller is powered on.

Sorry for didn't make it clear in the guide book, and our colleague is improving it.

Thanks,
Scott

**Comment by scotthsl** [comment]
Hot-plug may damage the circuit between Controller and modules, so please turn off the power firstly before plugging/unplugging modules.
