### ISSUE TITLE
Laser job can start with door open with door detection enabled

### ISSUE THREAD

**Issue by flynny75** [Snapmaker/Snapmaker2-Controller#101]
As posted about in the forum

https://forum.snapmaker.com/t/enclosure-door-detection-not-checked-at-start/17744

With the door open in the preparing stage (setting work origin, running boundary), I can click start and the job will start without noticing the door is open.

The laser job should not be able to start while the door is open (if door detection is enabled)

**Comment by ldp7** [comment]
@flynny75 

Thank you for reporting this issue.

We have set the laser safety limit in the controller firmware, which means that the laser power will stay 0.5% when the door is opened.

See those codes:

Functions

> void Enclosure::HandleDoorOpened() {
  LOG_I("door opened!\n");
  systemservice.PauseTrigger(TRIGGER_SOURCE_DOOR_OPEN);
  if (laser.IsOnline())
    laser.SetPowerLimit(TOOLHEAD_LASER_POWER_SAFE_LIMIT);
>  event_state_ = ENCLOSURE_EVENT_STATE_OPENED;
}
> void Enclosure::HandleDoorClosed() {
  LOG_I("door closed!\n");
  systemservice.ClearSystemFaultBit(FAULT_FLAG_DOOR_OPENED);
> if (laser.IsOnline())
    laser.SetPowerLimit(TOOLHEAD_LASER_POWER_NORMAL_LIMIT);
}


Limit definition:
> #define TOOLHEAD_LASER_POWER_SAFE_LIMIT   (0.5)
#define TOOLHEAD_LASER_POWER_NORMAL_LIMIT (100)
#define TOOLHEAD_LASER_CAMERA_FOCUS_MAX   (65000)

We have tests this power limit with an enclosure, and it does work well and the power stays very low.

It may be an occasional bug in firmware and please update the lasted version via this [link](https://forum.snapmaker.com/t/snapmaker-2-0-firmware-updates-and-downloads/5443/13)

Cheers 
Edwin
