### ISSUE TITLE
Feature Request: Enclosure should start up with lights on by default

### ISSUE THREAD

**Issue by Galindorf** [Snapmaker/Snapmaker2-Controller#122]
# 🐞 feature request

### Is your feature request related to a problem? Please describe.

On startup, enclosure lights are automatically off, they have to be turned on manually in an awkward fashion on a separate screen of the touch pad. 
### Describe the solution you'd like?
When the Snapmaker with enclosure starts up, please have the lights be "on" by default.

**Comment by iamrecursion** [comment]
Duplicate of #65.

**Comment by Snapmaker-support** [comment]
Hi friend,
The coming new firmware that will support the feature is scheduled to be released this month.

**Comment by scyto** [comment]
i can confirm this is fixed, yay! thanks snapmaker. time to close the issue :-)

**Comment by xhycode** [comment]
This issue has been supported in [V1.13.2](https://forum.snapmaker.com/t/snapmaker-2-0-firmware-updates-and-downloads/5443/17) and later, please use the latest firmware.
