### ISSUE TITLE
Cancel function on bed in nozzle heating

### ISSUE THREAD

**Issue by yhira1023** [Snapmaker/Snapmaker2-Controller#185]
After bed heating started ,can't cancel commands until heating compleated.
I have to wait several time or power off machine.
I hope forced interruptible cancel function.

**Comment by xhycode** [comment]
Hi yhira1023.
This problem does bring bad experience
We have already solved it in the upcoming release, so you can pause/stop while waiting for the heating process
Expected to be released next Monday

**Comment by yhira1023** [comment]
I am happy and appreciate to hear from you!

**Comment by xhycode** [comment]
The firmware has been released and you can download the [v1.14.1](https://forum.snapmaker.com/t/snapmaker-2-0-firmware-updates-and-downloads/5443/18) upgrade here.
I will close this issue and if still have the same problem you can open it again.
I hope this will bring you a better experience.
