### ISSUE TITLE
Feature Request - Octopi with OctoDash on Screen

### ISSUE THREAD

**Issue by bf8392** [Snapmaker/Snapmaker2-Controller#253]
It would be extremely cool if it would be possible to run octoprint DIRECTLY on the snapmaker. If this is not possible for some reason (haven't looked into it) it would be cool to let octodash display when octoprint is connected...

**Comment by snapmaker-lixiaolong** [comment]
octoprint can be connected to snapmaker 2.0 and 1.0 models via the miniUSB port

**Comment by snapmaker-lixiaolong** [comment]
octoprint can be connected to snapmaker 2.0 and 1.0 models via the miniUSB port

**Comment by bf8392** [comment]
Yeah but it's about using the screen to display stuff from octoprint
