### ISSUE TITLE
After power Off/On always hook to WiFi that was used during first setup and no Forget Wi-Fi option

### ISSUE THREAD

**Issue by tamer1an** [Snapmaker/Snapmaker2-Controller#73]
### Expected: 

1) After power Off/On machine connected to the same WiFI network that was connected previous 
2) Or at least Forget Network option could be an faster solution :feelsgood: 

I had stock firmware before updating to the latest Snapmaker2_V1.11.4 114
https://forum.snapmaker.com/t/snapmaker-2-0-firmware-updates-and-downloads/5443/12?u=tamer1an

### Before firmware update: 

Machine always connected to the same WiFi that was active before shutdown
After wake up it was connected to the same WiFI network again

### After firmware update:

After Power On machine often connecting to the network that was used on initial unboxing stage or stays not connected to WiFI at all and I have to type a complex password every time :finnadie: and there is no forget WiFi network option  

![144864113_2102664336541857_8250280126461893052_o](https://user-images.githubusercontent.com/956869/106953416-a9385880-6732-11eb-9ec7-6b0c2fa3eb41.jpg)

![146582133_2103207546487536_6870597048129302220_o](https://user-images.githubusercontent.com/956869/106953438-ae95a300-6732-11eb-8f42-057003e3f566.jpg)

**Comment by KoolFrank87** [comment]
I too am having this exact problem.  The A350 is forgetting the WiFi password after power cycling. Very annoying. :-(

**Comment by samvanh** [comment]
Same issue on latest firmware. Wifi connection does not persist across restarts.

**Comment by samvanh** [comment]
Don't think this is an HMI issue but rather a software bug.

**Comment by kahuwi** [comment]
Same issue on latest firmware. Wifi connection not remembered.
This is a QA oversight that needs to be fixed ASAP

**Comment by dusekdominik** [comment]
Same issue.

**Comment by thejerry1** [comment]
Same issue.

**Comment by samvanh** [comment]
To the developers: the issue doesn't seem to be in password retention but rather a bug in the initial connection. 

Expected use: 
Switch on the snapmaker, wait a couple of minutes, connect automatically to last wifi network

Actual:
No wifi connection established. 

2 possible workarounds:
1. Settings -> wifi -> select wifi network and type in passwords again
2. Settings -> wifi -> toggle wifi switch off and on.  Wait and couple of secs and it will connect to last network without prompting for password.

**Comment by dwienie** [comment]
@samvanh  the second workaround you mention  will that solve the issue forever or  you need to do that every time the wifi connection is not established?

**Comment by samvanh** [comment]
> @samvanh the second workaround you mention will that solve the issue forever or you need to do that every time the wifi connection is not established?

Every time... But at least you don't need to re-enter the password

**Comment by kahuwi** [comment]
This sequence needs to happen automatically on system power up.   When the snapmaker is not close at hand, having to go to the unit to manually connect to wifi is NOT the way network based system work in the real world.  On my setup, the power is turned on remotely and the snapmaker is in another building away from my computer.

**Comment by dwienie** [comment]
> This sequence needs to happen automatically on system power up. When the snapmaker is not close at hand, having to go to the unit to manually connect to wifi is NOT the way network based system work in the real world. On my setup, the power is turned on remotely and the snapmaker is in another building away from my computer.

Totally agree

**Comment by tlaurion** [comment]
Same issue.
Workarounds are to be done at each reboot:

> To the developers: the issue doesn't seem to be in password retention but rather a bug in the initial connection.
> 
> Expected use:
> Switch on the snapmaker, wait a couple of minutes, connect automatically to last wifi network
> 
> Actual:
> No wifi connection established.
> 
> 2 possible workarounds:
> 
>     1. Settings -> wifi -> select wifi network and type in passwords again
> 
>     2. Settings -> wifi -> toggle wifi switch off and on.  Wait and couple of secs and it will connect to last network without prompting for password.

**Comment by ncurley999** [comment]
I'm having the same issue unfortunately.

**Comment by tamer1an** [comment]
Thanks for the report guys, I found a corresponding issue in the software repo. 

https://github.com/Snapmaker/Luban/issues/788

Please leave ur comment also there to escalate this further

**Comment by slipperysam1984** [comment]
Same issue on A250 :-(

**Comment by genemyers** [comment]
was this ever addressed?

**Comment by NiteCrwlr** [comment]
I'm having the same problem. A350, no wifi connection after machine reboot. Latest version Snapmaker2_V1.12.0.

**Comment by tabledevil** [comment]
Same Issue on my A350. Is there a way to downgrade the firmware again?

**Comment by tamer1an** [comment]
Looks like it was fixed with the latest update, check it out guys. Re open in case if it still not working for you.
