### ISSUE TITLE
Cannot disable door detection

### ISSUE THREAD

**Issue by flynny75** [Snapmaker/Snapmaker2-Controller#9]
https://github.com/Snapmaker/Snapmaker2-Controller/blob/122d90d0a25db256b1a3eead63d6212f74e84ff7/snapmaker/src/module/enclosure.cpp#L182

The enabled flag is never assigned. The default value is true, thus the door event is always processed and door detection cannot be disabled. I suspect it is meant to be assigned in the Enable and Disable methods.

**Comment by scotthsl** [comment]
Thanks a lot , will check and fix it!

**Comment by ITmaze** [comment]
When you close an issue it's customary to link the commit that fixed it so
that if there's subsequently a problem, the issue can be reopened.

This makes for a much better way of tracking the relationship between the
code and the issue.

--
finger painting on glass is an inexact art - apologies for any errors in
this scra^Hibble

()/)/)() ..ASCII for Onno..
