### ISSUE TITLE
Automatic power supply fan speed

### ISSUE THREAD

**Issue by mr-manuel** [Snapmaker/Snapmaker2-Controller#90]
Hi,

the fan of the power suffly is spinning the whole time at 100%, even the Snapmaker 2.0 is idle and the power supply is producing no heat. Is it possible to turn off the fan if the Snapmaker is idle? Greater would even be if it's possible to control the power supply fan by the internal temperature.
E.g.:
* No heat = fan off
* Some heat = fan at 50%
* Hot = fan at 100 %

**Comment by xhycode** [comment]
I am very sorry to give you a bad user experience.
The fan of the power supply is hardware controlled. So your suggestion cannot be realized.
Sorry again for the inconvenience!

**Comment by mr-manuel** [comment]
Ok, thank you. Maybe it would be an idea to optimize hardware for future builds :)

**Comment by xhycode** [comment]
This is a very good idea, we will optimize the power in the next version, thank you for your support!

**Comment by scotthsl** [comment]
New power module will enter mass production. so close this issue.
